### ISSUE TITLE
Cart Feature 

### ISSUE THREAD

**Issue by howardsolutions** [thinhphungdev/pizza-order#4]
🛒 Cart feature
Also be Global state allow accessible through entire component in the application.
User CAN
👉 Add pizza item to cart
👉 View the cart overview component (about total item quantity & total price) at the footer when cart is not empty
👉 Clear everything from cart
👉 Decrease or increase or delete the item quantity directly inside the cart
👉 Using cart data (about total item quantity, totalprice,...) to create new order.

**Comment by thinhphungdev** [comment]
https://github.com/thinhphungdev/pizza-order/issues/4

**Comment by howardsolutions** [comment]
https://github.com/thinhphungdev/pizza-order/pull/2

**Comment by howardsolutions** [comment]
MERGED Pull request: https://github.com/thinhphungdev/pizza-order/pull/2

**Comment by howardsolutions** [comment]
https://github.com/thinhphungdev/pizza-order/pull/2
